name: "Main"

on:
  pull_request:
    types: [ closed ]
    branches:
      - 'ADD-\d+'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy-Main
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_PRODUCTION}}
          heroku_email: "romangusev2001@mail.ru"
